### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by nilleb** [atom-community/sync-settings#141]
[Enter steps to reproduce below:]

On Windows 8.1
1. install the sync-settings plugin
2. configure it to use an existing token/git id
3. execute the command 'sync settings: restore'

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /C:/Users/bellinsalarin/.atom/packages/sync-settings/lib/sync-settings.coffee:288

TypeError: Cannot read property '0' of undefined
    at file:///C:/Users/bellinsalarin/.atom/packages/sync-settings/lib/sync-settings.coffee:189:68
    at C:\Users\bellinsalarin\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:342:17
    at callCallback (C:\Users\bellinsalarin\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
    at IncomingMessage.<anonymous> (C:\Users\bellinsalarin\.atom\packages\sync-settings\node_modules\github\index.js:796:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:889:12)
    at doNTCallback2 (node.js:438:9)
    at process._tickCallback (node.js:352:17)
```

### Commands

```
     -1:22.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -1:19.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:19 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:17.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:17.7.0 sync-settings:restore (atom-text-editor.editor)
     -0:12.4.0 sync-settings:check-backup (atom-pane.pane.active)
     -0:03.2.0 sync-settings:restore (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "9b041667-9313-4293-a4b9-38d38e89813a",
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "gistId": "9c18b3089454b0489a05"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by qianlifeng** [comment]
I have the same issue

**Comment by ukurasmus** [comment]
Is your gist public or secret? I had same issue when I created a secret gist, converting it into public solved the problem for me.

**Comment by nilleb** [comment]
Secret gist. I have to say that on Mac OS X I can sync with the same
token/gist. The problem is visible on Windows 8.1.

**Comment by nilleb** [comment]
I will try Monday changing the gist visibility. Thanks

**Comment by nilleb** [comment]
Sorry for the delay. Even changing the visibility of the gist, I still get this error

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by nilleb** [comment]
Thanks Dirk!

**Comment by hvmonteiro** [comment]
Hello, 
I have the same problem.
I'm using it Atom on a Windows machine in a corporate network accessing internet using a properly configured proxy in Atom (ex: I can download packages, etc.).

I might think that it's because of proxy settings not being correctly handled.

Taking a look insde 'sync-settings.coffee' around the error line (for me it was at line 201) we have this block:
  createClient: ->
    token = atom.config.get 'sync-settings.personalAccessToken'
    console.debug "Creating GitHubApi client with token = #{token}"
    github = new GitHubApi
      version: '3.0.0'
      # debug: true
      protocol: 'https' <--- Line 201
    github.authenticate
      type: 'oauth'
      token: token
    github

Cheers,
Hugo

**Comment by dirk-thomas** [comment]
@hvmonteiro Which version of this package are you using? If you are using the latest released version you need to update to the current master branch which contains a patch for working with proxies (see #167).

**Comment by MrCitron** [comment]
@dirk-thomas can you please explain how to update the plugin to current master version ?
Thanks

**Comment by dirk-thomas** [comment]
The proxy fix is now also available in the latest release (v0.7.0). You don't need a custom checkout anymore. Please just upgrade the package through the Atom UI.

**Comment by jerone** [comment]
@nilleb @qianlifeng @ukurasmus @hvmonteiro @MrCitron  Can you guys confirm this has been fixed in the latest release?

**Comment by MrCitron** [comment]
Hi @jerone , still not fixed for me.
I upraded Atom and then this plugin, but I was not able to backup or restore my settings at work behind a corporate proxy.

**Comment by jerone** [comment]
And did you setup Atom to support proxy: https://atom.io/docs/latest/getting-started-installing-atom#setting-up-a-proxy ?

**Comment by MrCitron** [comment]
Yes I followed the first link (created .apmrc file with proxy config) and I am able to download packages right from atom for example.
I will try the instructions given in the two other links next week

**Comment by jerone** [comment]
We previously had problems with people using proxies. Those issues should have been fixed when https://github.com/atom-community/sync-settings/pull/167 was merged. Confirmed on https://github.com/atom-community/sync-settings/issues/142.

Now is the question, why it doesn't work for you and does work for others...?

**Comment by hvmonteiro** [comment]
Hello,
I can confirm it's working for me with the latest update.
Working correctly using the configured proxy now.
Thanks & Cheers!

**Comment by jerone** [comment]
@hvmonteiro Great to hear! Can you please describe your steps to correctly configure the proxy, so we can help others too. Thanks!

**Comment by MrCitron** [comment]
Finally working for me as well
My atom settings were good, but I had a an error on system env.
I had to change my https_proxy var from `https_proxy=https://myproxy:port` to `https_proxy=http://myproxy:port`

Thanks for all the help

**Comment by hvmonteiro** [comment]
Here are a few notes I took that helped me configuring the proxy on NPM/APM and Atom:

#### Set proxy for 'apm':
apm config set ftp-proxy ftp://proxy:8080
apm config set http-proxy http://proxy:8080
apm config set https-proxy https://proxy:8080
apm config set proxy http://proxy:8080
apm config set strict-ssl=false
_-or-_
apm config set strict-ssl=true

**Comment by Kingmylesbajo** [comment]
TypeError: Cannot read property '0' of undefined
    at IncomingMessage am having similar problem can someone please help me 

/*Here is my html code*/
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Weather App</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head> 
    <body>
        
        <form action="/" method="POST">
        <label for="cityInput">cityName: </label>
        <input id="cityInput" type="text" name="cityName">
        <button type="submit">GO</button>
        </form>

        <script src="" async defer></script>
    </body>
</html> 


//Here is my app.js code//

const express=require("express");
const https=require("https");
const bodyParser=require("body-parser");
const {response}=require("express");
const app=express();
app.use(bodyParser.urlencoded({extended:true}));



app.get("/",function(req,res){
    res.sendFile(__dirname +"/index.html");

});


app.post("/",function(req, res){

  const query=req.body.cityName;
  const appId="cbb82ce079c621c839ff84be7f96ca23";
  const units="metric";
  const  url="https://api.openweathermap.org/data/2.5/weather?q="+ query +"&appid "+ appId +"=&units=" + units;

   https.get(url,function(response){
   console.log(response.statusCode);

    response.on("data",function(data){
    const weatherData  =JSON.parse(data);


    const icon=weatherData.weather[0].icon;
    const weatherDiscription=weatherData.weather[0].description


    const imageURL="http://openweathermap.org/img/wn/"+ icon+"@2x.png";
     const temp=weatherData.main.temp;


     res.write("<h1>the temperature in "+ query +" is " + temp + "degrees Celcius</h1>");
     res.write("<p>The current weather is " +  weatherDiscription + "</p>");
     res.write("<img src=" + imageURL +">");

     res.send();
     });




 });

})

 app. listen(3000,function(req, res){
     console.log("the sever is running at port 3000");

 })   

/*Here is what my browser shows */

This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
