### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/node_modules/github/api/v3.0.0/routes.json'

### ISSUE THREAD

**Issue by jsnelgro** [atom-community/sync-settings#194]
# TLTR: This is a known issue, without solution. The work-around is to restart Atom.

---

[Enter steps to reproduce below:]
1. click "Update All"

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/jhs/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/jhs/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/jhs/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/jhs/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/jhs/.atom/packages/sync-settings/lib/sync-settings.coffee:300:16)
    at Object.SyncSettings.checkForUpdate (/Users/jhs/.atom/packages/sync-settings/lib/sync-settings.coffee:61:21)
    at Immediate._onImmediate (/Users/jhs/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```
### Commands

```
     -9:09.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:23.4.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-monokai.theme-one-dark-ui)
     -3:21.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:20.8.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:20.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:19.7.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:15.3.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:15 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:13.8.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:13.5.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-monokai.theme-one-dark-ui)
     -3:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:11.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:10.7.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:06.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:06.3.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:50.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-monokai.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "editorconfig",
      "linter-jscs"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "...",
    "_lastBackupHash": "...",
    "gistId": "...",
    "personalAccessToken": "..."
  }
}
```
### Installed Packages

``` coffee
# User
api-docs, v0.0.4
atom-beautify, vundefined
atom-cli-diff, v1.3.0
atom-handlebars, v1.3.0
atom-html-preview, v0.1.16
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
color-picker, v2.1.1
cson, v2.0.1
file-icons, v1.6.18
git-diff-details, v0.23.0
highlight-selected, v0.11.2
language-haml, v0.23.15
language-javascript-jsx, v0.3.7
language-matlab, v0.2.0
language-slim, v0.5.0
language-spacebars, v0.2.2
linter, v1.11.3
linter-bootlint, v1.0.2
linter-coffeelint, v1.1.2
linter-haml, v1.1.0
linter-htmlhint, v1.0.3
linter-js-standard, v3.2.1
linter-ruby, v1.2.2
monokai, v0.18.0
pdf-view, v0.48.0
pigments, v0.24.4
react, v0.14.1
relative-numbers, v0.5.0
set-syntax, v0.3.0
standard-formatter, v2.0.0
sync-settings, v0.7.0
vim-mode, v0.64.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
I can confirm the stacktrace happening when updating from version 0.6 to 0.7. But it seems to have no negative impact afterwards. The package seems to work find.

@groupsky @jerone 0.7 replaces the dependency `github` with `guthub4`. During the update Atom seems to access a file from the `github` dependency which has already been removed. Any idea why that is the case?

**Comment by gsklee** [comment]
Same here.

**Comment by danielsmink** [comment]
+1

1. Updated the plugin in an open project

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/danielsmink/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/danielsmink/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/danielsmink/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
  2x -4:09.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:09.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -4:08.8.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -4:08.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:00.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:00.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:00.8.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -4:00.8.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -3:59 core:save (atom-text-editor.editor.is-focused)
     -3:42.4.0 core:copy (atom-text-editor.editor.is-focused)
     -3:37.4.0 core:paste (atom-text-editor.editor.is-focused)
     -3:32.6.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -3:32.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:16.1.0 core:delete (atom-text-editor.editor.is-focused)
     -2:15.2.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -2:14.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "8cc8d8fb-8e90-4d88-9f9b-9f16827bc957",
    "_lastBackupHash": "650a6325a91397dd7993db499bc728a310a43c3b",
    "gistId": "1ebdbb01654e142241f3",
    "personalAccessToken": "eac6c87681ea97f0f461f4bfddb7d25d240a6dcb"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.26
atom-typescript, v8.3.0
docblockr, v0.7.3
emmet, v2.4.2
language-docker, v1.1.6
linter, v1.11.3
linter-eslint, v7.0.0
linter-php, v1.2.0
pigments, v0.24.4
save-session, v0.16.0
seti-syntax, v0.4.1
seti-ui, v0.9.1
sync-settings, v0.7.0
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by jerone** [comment]
Can't confirm this on Windows 7 Atom v1.6.0-beta7 and not on Windows 8.1 Atom 1.5.4.

**Comment by jerone** [comment]
I'm thinking ti has something to do with updating within Atom, while Atom is open. I've seen this happen a few times (with themes mostly) where files where locked by Atom, which resulted in a failed update.

Can someone confirm this issue still happening **while Atom wasn't open**?!

**Comment by jerone** [comment]
Oke, I can reproduce now:

1. Install sync-settings v0.6.0: `apm install sync-settings@0.6.0`
2. Make sure valid credentials are entered in the `config.cson`!
3. Start Atom.
4. Go to settings and update sync-settings.
5. See error show up.

Just as I thought; an locked file while updating. This shouldn't happen when Atom is closed.

Looking at the [API](https://kaizensoze.github.io/node-github/) I can't find any function to release/destroy the GitHub constructor...

**Comment by jerone** [comment]
The work-around btw is to reinstall the package when Atom is closed: `apm install sync-settings`.

**Comment by pstadler** [comment]
I had the same error dialog after updating to 0.7.0. Restarting Atom solved the problem.

**Comment by Fipo** [comment]
Restart Atom works just fine ;)

**Comment by jerone** [comment]
Related I think: https://github.com/atom/atom/issues/9559

**Comment by vsivsi** [comment]
+1  On OS X 10.11.3 with Atom 1.5.4

**Comment by dirk-thomas** [comment]
I have removed the `BLOCKING` label since the package is working afterwards just find.

It seems to be OS X specific. All reports have been from that platform only.

**Comment by jerone** [comment]
> It seems to be OS X specific.

Aldo most of them are on OSX, I've seen a few on Linux and confirm the issue on Windows myself.

**Comment by dirk-thomas** [comment]
I have updated the title to match the proposed change to the notification package (atom/notifications#113).

**Comment by jerone** [comment]
I've added the "Help wanted" tag. Aldo we have a work-around (just restarting Atom), if someone can provide us a real solution would be great...

**Comment by Nephrited** [comment]
+1 to this issue, see above. Accidentally created a new issue before seeing this one.

**Comment by RVN-BR** [comment]
sorry... created #231 without seeing this

**Comment by zhurai** [comment]
I got this error too. Was going to submit a new issue but checked issues list just in case...

I'm on Windows 7.Atom v1.5.4

**Comment by diogo-gomes** [comment]
**+1**

Atom Version: 1.6.0
System: Ubuntu 14.04.4
Thrown From: sync-settings package, v0.7.2

**Comment by AliShug** [comment]
Same here, Windows 10:

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\...\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\routes.json'

```
At fs.js:584

Error: ENOENT: no such file or directory, open 'C:\Users\...\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at Object.module.exports (C:\Users\...\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:22:33)
    at new module.exports (C:\Users\...\.atom\packages\sync-settings\node_modules\github\index.js:184:26)
    at Object.SyncSettings.createClient (file:///C:/Users/.../.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (file:///C:/Users/.../.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (file:///C:/Users/.../.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -1:09.5.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
undefined -0:11.3.0 core:move-right (atom-text-editor#autocomplete-python.extraPaths.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "openEmptyEditorOnStart": false
  },
  "sync-settings": {
    "_analyticsUserId": "...",
    "_lastBackupHash": "...",
    "gistId": "...",
    "personalAccessToken": "..."
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.14.1
autocomplete-glsl, v0.2.3
autocomplete-python, v1.7.2
build, v0.60.0
hex, v0.6.2
highlight-selected, v0.11.2
language-glsl, v2.0.1
merge-conflicts, v1.4.2
minimap, v4.23.2
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
python-tools, v0.6.7
release-notes, v0.53.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by xenithorb** [comment]
I just started seeing this on Linux after doing a set of package updates. Restarting atom has no effect.

**Comment by xenithorb** [comment]
For me this worked to alleviate the error message on every atom start:

```
apm uninstall sync-settings && apm install sync settings
```

**Comment by dirk-thomas** [comment]
@xenithorb This specific problem from this issue is indeed be resolved by restart Atom. You might have a slightly different problem if it persists after restart. Since you also commented [here](https://github.com/atom-community/sync-settings/issues/211#issuecomment-266812112) I asked you there for more information.

**Comment by dirk-thomas** [comment]
While this problem was common a while ago it shouldn't be the case anymore. Therefore I will close this now.

**Comment by misode** [comment]
I just downloaded Atom today and got this error. Restarting Atom doesn't seem to fix it.
