### ISSUE TITLE
Telling me to restore settings every time I open a window

### ISSUE THREAD

**Issue by alexb148** [atom-community/sync-settings#497]
The extension is showing a yellow notification telling me "Your settings have changed since your last backup." They haven't - I haven't published any settings changes in weeks.

This appears every time I launch Atom, or open a new window.

Latest versions of Atom and Sync-Settings extension.

What's going on with this extension lately? There seems to be a new update every few days, and I'm now getting issues where it has always worked fine before.

**Comment by UziTech** [comment]
This package hasn't been maintained in a while. I have been updating it to allow for more functionality.

The restore notification pops up because you have the setting checked to check the backup on startup and your backup is different from your current settings. If you uncheck that setting it will no longer notify you on startup.

If you click "View Diff" on the notification it will show you what has changed.

If there are other issues I would be happy to hear about them to try and get them resolved.

**Comment by UziTech** [comment]
If you have any other questions or issues feel free to open other issues. Thanks.

**Comment by IronSavior** [comment]
I'm having this problem and my settings aren't changing day to day. The diff shows no changes and when I tell it to make a backup, the commit has no changes. See screenshots below.

![image](https://user-images.githubusercontent.com/174661/75913787-67a77b00-5e08-11ea-8f97-a4e8aa09d092.png)

![image](https://user-images.githubusercontent.com/174661/75913822-7f7eff00-5e08-11ea-8220-cfa46ad5cbfe.png)

**Comment by IronSavior** [comment]
> If you have any other questions or issues feel free to open other issues. Thanks.

Can we reopen this one, @UziTech ?

**Comment by FlatlineTV** [comment]
Came here to report on the issue as well. Been using this package for couple years and it's never had this issue until last week.

![03-04-2020 04-17-55PM](https://user-images.githubusercontent.com/13840075/75935400-f41b6300-5e33-11ea-9443-233ef9464509.png)

I see this window every time I open a new window. I tried clicking restore, backup, etc. Will always show this window when before it would mention my settings are synced. No settings have been changed, I hardly do.

Thanks!

**Comment by UziTech** [comment]
@FlatlineTV Try clicking View Diff and seeing what it thinks has changed.

**Comment by FlatlineTV** [comment]
@UziTech I get the same notification every single time I hit Ctrl+Shift+N (new window)

![image](https://user-images.githubusercontent.com/13840075/75950338-b6333480-5e5d-11ea-9c92-09f02fa11223.png)

**Comment by UziTech** [comment]
@FlatlineTV There is no need to backup config.cson since Sync-Settings already backs up settings to settings.json

It does that so it can remove certain settings like _lastBackupTime and things that should not be backed up like your Personal Access Token.

The only way I know how to fix your issue is to not backup config.cson since your config.cson file will always be changed after you back up to save the last backup time.

**Comment by FlatlineTV** [comment]
@UziTech I guess I'll just Stop the Automatic Check for now. But just wanted to report this issue was never present in the past:

![aKmDlvZ](https://user-images.githubusercontent.com/13840075/75958315-cdc7e880-5e70-11ea-9a02-7df1c35792ca.gif)

**Comment by stefanocoretta** [comment]
I'm having the same issue. In my case, the main divergence in backups is in the `packages.json` file.

**Comment by UziTech** [comment]
@FlatlineTV it wasn't there in the past because it would only show the notification if the backup changed not if the local settings changed. I suppose we could have two settings, one to notify if the backup changed and one to notify if the current settings changed.  If you want to create a PR for that I would be happy to review it.

**Comment by UziTech** [comment]
@stefanocoretta if you update a package it will notify you to run the backup since your backed up packages is now different from your local packages.

I suppose we could make it not check the package versions in the diff if the always install latest packages setting is checked.

**Comment by IronSavior** [comment]
> I suppose we could make it not check the package versions in the diff if the always install latest packages setting is checked.

I don't think that would necessarily be a good change. Versions matter in a lot of cases. I'm okay with it not asking me, though. All backup versions would be retained, after all.

**Comment by UziTech** [comment]
@IronSavior yes the versions would still be stored in the backup just the diff wouldn't show a difference if just the versions are different ***and*** `Always Install Latest Version` setting is checked

**Comment by UziTech** [comment]
I created PR #500 that will prevent "Check Backup" from failing if `Always Install Latest Version` is checked and the only difference between the backup and local settings is the package version.

The Diff View still shows when package versions are different.

@stefanocoretta and @IronSavior I would like to hear from you two, and anyone else, if this sounds like a good solution before I merge it.

**Comment by IronSavior** [comment]
> @IronSavior That is strange. I wonder what happens if you click restore then view the diff. Does it still show them as different?

Restoring from the backup did stop the problem where it showed every line changed. Thanks for the tip.

> I created PR #500 that will prevent "Check Backup" from failing if `Always Install Latest Version` is checked and the only difference between the backup and local settings is the package versions.
> 
> The Diff View still shows when package versions are different.
> 
> @stefanocoretta and @IronSavior I would like to hear from you two, and anyone else, if this sounds 
> like a good solution before I merge it.

I approved the PR. That change works for me and the logic seems correct.

**Comment by UziTech** [comment]
v4.3.2 should fix the issue with notifying about package version changes when `Always Install Latest Version` is checked.

Is there any other situations where the notification should be prevented?

**Comment by FlatlineTV** [comment]
@UziTech I have  "Always Install Latest Version" & "Auto Check Backup" is checked. Everytime I open a new window, the window I displayed before is still showing.

**Comment by UziTech** [comment]
does the diff only show that the package versions changed?

**Comment by UziTech** [comment]
@FlatlineTV if you are still backing up `config.cson` than `Always Install Latest Version` won't prevent the notification. The only way to prevent the notification would be to stop backing up `config.cson` or uncheck `Auto Check Backup`.

**Comment by mroavi** [comment]
I'm having the same issue that @FlatlineTV showed. In my case this is what the `diff` shows:

![image](https://user-images.githubusercontent.com/19517248/76957824-cb589a80-6916-11ea-9d15-410005e63b2a.png)

I get this pop up with both `Always Install Latest Version` checked and unchecked. This might give a clue to detect the root problem. It seems related with automatic addition/removal of newlines.

**Comment by UziTech** [comment]
@mroavi it looks like you have a file called `init.coffee` in your backup that is not on your local computer. Your issue should be solved by checking `Remove Unfamiliar Files` and clicking `Backup`. Or you can manually delete that file in your backup.

**Comment by mroavi** [comment]
The `init.coffee` file is present on my local computer. I use it to enforce a specific grammar or syntax when creating new files as explained [here](https://discuss.atom.io/t/how-can-i-make-all-new-files-open-with-a-specific-grammar-or-syntax/20754).
![image](https://user-images.githubusercontent.com/19517248/76964153-8fc3cd80-6922-11ea-9ccd-98324e586217.png)
I did not add that file to the backup manually. It was automatically added by `sync-settings`.

**Comment by UziTech** [comment]
@moroavi The green file name means it was found in your backup but not on your local computer. Your local file could be named `init.json`.

**Comment by mroavi** [comment]
I don't understand why it doesn't find it on my local computer. It's right there and it's working too.

**Comment by UziTech** [comment]
Yes. it will only find one and defaults to `init.js` if both exist.

It looks like Atom only sees the `init.js` as well if both exist. https://github.com/atom/atom/blob/d7f7b4f0aa4096df04e88a1b5f8e5e6887e96143/src/atom-environment.js#L1521

**Comment by UziTech** [comment]
> By the way, when I first created the backup, it actually automatically chose the name init.coffee for the gist. Could that also be a source of the problem?

That could be

**Comment by mroavi** [comment]
I will get rid of `init.coffee` then. Thanks a lot @UziTech .

**Comment by UziTech** [comment]
I'm going to close this since these issues aren't related and it would be easier to debug them individually.

If anyone has notification that shouldn't be there please open a new issue with a screenshot of the diff view.
